apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-command-vcluster"
spec:
  title: "Test of using the vCluster CLI"
  description: "Test of creating a virtual cluster using the vcluster CLI"
  publish:
    image: $(image_repository)/labs-vcluster-testing/lab-command-vcluster-files:$(workshop_version)
    files:
    - directory:
        path: .
      includePaths:
      - /workshop/**
      - /resources/**
      - /exercises/**
      - README.md
      excludePaths:
      - /workshop/.hugo_build.lock
      - /workshop/resources/**
  workshop:
    files:
    - image:
        url:  $(image_repository)/labs-vcluster-testing/lab-command-vcluster-files:$(workshop_version)
    packages:
    - name: vcluster
      files:
      - path: .
        image:
          url: ghcr.io/educates/educates-extension-packages/vcluster:v0.30.3
  session:
    namespaces:
      budget: large 
      security:
        policy: baseline
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: false
      editor:
        enabled: true
      vcluster:
        enabled: false
      files:
        enabled: true
    # We need cluster rolebindings to allow the vcluster CLI to create virtual clusters
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_name)-vc
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: edit
      subjects:
      - kind: ServiceAccount
        namespace: $(session_namespace)
        name: $(service_account)
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: $(service_account)
        namespace: $(session_namespace)
        labels:
          app.kubernetes.io/managed-by: Helm
        annotations:
          meta.helm.sh/release-name: $(session_name)
          meta.helm.sh/release-namespace: $(session_namespace)
